# Stage 1: Build
FROM node:22-alpine AS build

RUN apk add --no-cache npm

WORKDIR /app

COPY package.json ./
RUN npm install

COPY . .
COPY ./shared ./shared

RUN npm run build

# Stage 2: Run
FROM node:22-alpine
RUN apk add --no-cache npm

WORKDIR /app

COPY --from=build /app ./

EXPOSE 3000

CMD ["npm", "run", "start"]