export const HttpResponse = {
  SERVER_ERROR: "Internal server error",
  USER_EXIST: "User already exist",
  PAGE_NOT_FOUND: "Route not found",
  USER_NOT_FOUND: "User not found",
  PASSWORD_INCORRECT: "Incorrect password, try again",
  NO_TOKEN: "Token not provided",
  OTP_INCORRECT: "Incorrect otp, try again",
  OTP_NOT_FOUND: "Otp not found",
  INVALID_CREDENTIALS: "Invalid credentials",
  USER_CREATION_FAILED: "User creation failed",
  USER_CREATION_SUCCESS: "User created successfully",
  UNEXPECTED_KEY_FOUND: "Unexpected key found",
  INVALID_EMAIL: "Invalid email address",
  RESET_PASS_LINK: "Link for resetting password is sended to email",
  TOKEN_EXPIRED: "Token not valid or expired!",
  PASSWORD_CHANGE_SUCCESS: "Password changed successfully!",
  UNAUTHORIZED: "Unauthorized access!",
  USERNAME_EXIST:"Username Already Exist",
  NO_PAYLOAD:"Payload not found",
  USERNAME_CHANGED: "Username has been changed successfully",
  SAME_USERNAME: "Cannot change to old username",
  RESOURCE_FOUND: "Resource found.",
  RESOURCE_UPDATED: "Resource updated.",
};
